services:
  db:
    image: postgres:15.3
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Livra_tura
      POSTGRES_USER: livratura
      POSTGRES_DB: livratura
    ports:
      - "5432:5432"
